[workspace]

members = [
    "analyser",
    "assembler",
    "gif_renderer",
    "glutin_frontend",
    "ines",
    "mos6502",
    "nes_specs",
    "nes_emulator",
    "nes_headless_frame",
    "nes_name_table_debug",
    "nes_palette",
    "nes_samples",
    "samples",
]
